### ISSUE TITLE
No events

### ISSUE THREAD

**Issue by kroese** [maciej-or/hikvision_next#10]
Hi,

Two questions:

  - What is the difference between this integration and the "official" one in HomeAssistant? Except for the alarm server, they seem to provide the same binary sensors?

 - I installed it and everything went fine, but I'm getting no events to trigger? The camera model is Hikvision DS-2CD2546G2-IS. To be fair, I also encountered the same problem using the "official" integration. I checked all settings multiple times, but I can't figure out why it is not working. I have "Send to Surveillance Station" enabled for all events, checked the admin rights, etc. Do you have any clue what could be wrong?

**Comment by maciej-or** [comment]
Hi,

Except alarm server and binary sensors this integration provides switches for events detection and switch for holiday mode (perhaps for NVRs only). Having switches you are able to arm cameras for away, at home or other scenarios at single click in HA.

For triggering events you need to have:
- enabled event
- checked Notify Surveillance Center in Linkage Method
- defined Areas, Regions, Lines (depends on event type)
- set Arming Schedule
- set alarm server destination to your Home Assistant

If notifications don't work pls share integration logs - described here [Reporting issues](https://github.com/maciej-or/hikvision_next#reporting-issues) then I could help more

**Comment by maciej-or** [comment]
thanks, I've downloaded logs you can delete from pastebin. Alarm server settings are crucial in passing notifications. Camera or NVR send event notifications to defined destination. In this case Home Assistant is the receiver and integration processes HTTP post into binary sensor trigger. You can let hikvision_next integration to set alarm server on camera by checking `Set alarm server using following address` during adding integration. You can verify that or set it manually in camera's admin panel:

<img width="1108" alt="image" src="https://user-images.githubusercontent.com/38075949/227765192-8ecd8fba-b46f-4a4e-89b4-b251a5c12f21.png">

IP should point your Home Assistant instance, port is set 8123 by default so update it if you use another one, the rest options should be the same as in the picture

**Comment by maciej-or** [comment]
I meant optional because you can do it manually as well. 

To raise security level I'd suggest whitelist HA IP only in camera IP filtering settings. There is no other way to communicate with HA than http, official integration does the same but in reversed direction - it calls ISAPI endpoint in given period, the downside are redundant requests and delays. ONVIF uses HTTP layer as well, unfortunately doesn't cover all acusense events.

Using alarm server notifications are `real-time`, that was the main motivation to write this integration, it may sound serious but they are only simple HTTP POSTs from camera or NVR to Home Assistant endpoint.
