### ISSUE TITLE
Getting Unexpect: Read Timeout when configuring NVR

### ISSUE THREAD

**Issue by cipacda** [maciej-or/hikvision_next#201]
Trying to set it with a NVR (Unexpected ReadTimeout:) that is on the same network and after I enter the credentials on the first screen I get the following: `Unexpected ReadTimeout:`

URL is set like this: http://192.168.1.10

**Comment by maciej-or** [comment]
Hi, 
This was reported here #181, I assume the cause is the same.
I think I found the bug, unfortunately it's in an external library used by the integration. Anyway I'll try to fix it.
Here https://github.com/MissiaL/hikvision-client/blob/master/hikvisionapi/hikvisionapi.py#L241 timeout should be passed as for the rest of the requests.

**Comment by maciej-or** [comment]
Default timeout is 5 seconds, should be enough to connect the device. Are you able to open `http://192.168.1.10/ISAPI/System/status` in web browser?

**Comment by cipacda** [comment]
Yes, I am able to access that. Also, I did try it again today and it seems to have worked, or at least I managed to complete the confirguration wizard.

The only thing that changed is that I had no HDD installed before.

**Comment by maciej-or** [comment]
https://github.com/maciej-or/hikvision_next/releases/tag/v1.0.18
