### ISSUE TITLE
Re-enabled cameras entity by itself

### ISSUE THREAD

**Issue by dolenec** [maciej-or/hikvision_next#213]
If I disable entity (let's say: motion detection) of some camera it is re-enabled by itself after some time).

Why is that? It seems that it's added as new entity ID.

**Comment by maciej-or** [comment]
It happens when integration reloads, for example when starting HA. Why? Switches and sensors are automatically disabled if related event has disabled `Notify Surveillance Center` flag because then they are useless. Enabling is also automatic to keep consistency. 
Entity IDs are generated based on the serial number so they are always the same.

**Comment by dolenec** [comment]
Is there any option for some setting to define this kind behave as for me it would be great that entity settings stay as it was set from me in HA neverless if HA is rebooted etc..

**Comment by maciej-or** [comment]
There is no such option at the moment. You can disable `Notify Surveillance Center` flag or comment out this line:
https://github.com/maciej-or/hikvision_next/blob/main/custom_components/hikvision_next/__init__.py#L95

**Comment by dolenec** [comment]
Great.. I will try it..

**Comment by dolenec** [comment]
This is working.. I hope that it won't be need to fix for every release..

**Comment by maciej-or** [comment]
I'm afraid it will be needed
